version: "3"
 
services:
  database:
        container_name: 'database_mysql'
        image: 'mariadb:latest'
        ports:
          - 3306:3306
        volumes:
          - ./data/mysqlVol/mysql:/var/lib/mysql
          - ./data/mysqlVol/logs/mysql:/var/log/mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: otb_segura_db
          MYSQL_USER: sa
          MYSQL_PASSWORD: sa2021
   
  php_service:
    container_name: 'apache_server'
    build: ./
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./html:/var/www/html
    expose:
      - 80
    ports:
      - 80:80
    depends_on: 
      - database